fc-instagram/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from posts.views import tag_post_list

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='posts:post_list'), name='index'),
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('explore/tags/<str:tag_name>', tag_post_list, name='tag_post_list'),
    path('members/', include('members.urls')),
    # path('media/<path:path>', views.media_serve)
]

# 특정 디렉토리가 왔을 땐 static을 사용해서 접두사를 붙임.
#
urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

fc-instagram/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('',
         views.post_list,
         name='post_list'),
    path('upload/',
         views.post_create,
         name='post_create'),
    # post의 pk를 찾을 때 이렇게 함.
    path('<int:post_pk>/comments/create/',
         views.comment_create,
         name='comment_create'),
    path('tag_search/',
         views.tag_search,
         name='tag_search'),
    path('<int:post_pk>/like_toggle/',
         views.post_like_toggle,
         name='post_like_toggle'),
]

fc-instagram/posts/models.py
# from django.contrib.auth.models import AbstractUser
import datetime
import re

from django.db import models
from django.conf import settings

# https://github.com/matthewwithanm/django-imagekit


class Post(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    author = models.ForeignKey(
        # Django가 기본적으로 제공하는 User 클래스
        # 'appname.modelname'
        # 'members.User',
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name='작성자',
    )

    photo = models.ImageField(
        '사진',
        upload_to='post',
    )

    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        through='PostLike',
        related_name='like_posts',
        related_query_name='like_post',
    )

    class Meta:
        verbose_name = '포스트'
        verbose_name_plural = f'{verbose_name} 목록'
        ordering = ('-pk',)

    def like_toggle(self, user):
        postlike, postlike_created = self.postlike_set.get_or_create(user=user)
        if not postlike_created:
            postlike.delete()


class Comment(models.Model):
    TAG_PATTERN = re.compile(r'#(?P<tag>\w+)')

    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        verbose_name='포스트',
        related_name='comments',
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        # 'members.User',
        on_delete=models.CASCADE,
        verbose_name='작성자',
    )
    contents = models.TextField()
    # 해시태그: 여러개
    hashtags = models.ManyToManyField(
        'Hashtags',
        blank=True,
        verbose_name='해시태그 목록',
    )
    # Comment의 save()가 호출 될 때,
    # content의 값을 사용해서 이 필드를 자동으로 채운 후 저장하기
    _html = models.TextField('태그가 HTML화된 댓글 내용', blank=True)

    class Meta:
        verbose_name = '댓글'
        verbose_name_plural = f'{verbose_name} 목록'
    # 멘션을 달면 나와 남이 바로연계됨.
    # mentions = models.ManyToManyField(
    #     'User',
    # )

    # 댓글 저장 후, content에 포함된 Hashtags 목록을
    # 댓글의 tags 속성에 set한다.
    # 원래 views에 있던걸 save 메소드 overriding으로 해치움.
    def save(self, *args, **kwargs):
        def save_html():
            # 저장하기 전에 _html필드를 채워야 함 (content값을 사용해서)
            self._html = re.sub(
                self.TAG_PATTERN,
                r'<a href="/explore/tags/\g<tag>/">#\g<tag></a>',
                self.contents,
            )

        def save_hashtags():
            # DB에 Comment저장이 완료된 후,
            #  자신의 'content'값에서 해시태그 목록을 가져와서
            #  자신의 'tags'속성 (MTM필드)에 할당
            hashtags = [Hashtags.objects.get_or_create(tag_name=tag_name)[0]
                        for tag_name in re.findall(self.TAG_PATTERN, self.contents)]
            self.hashtags.set(hashtags)

        save_html()
        super().save(*args, **kwargs)
        save_hashtags()

    @property
    def html(self):
        # 자신의 content속성값에서
        # "#태그명"에 해당하는 문자열을
        #  아래와 같이 변경
        #   <a href="/explore/tags/{태그명}>/">#{태그명}</a>
        # re.sub를 사용
        return self._html


class Hashtags(models.Model):
    tag_name = models.CharField(
        '태그명',
        max_length=64,
        unique=True,
    )

    def __str__(self):
        return self.tag_name

    class Meta:
        verbose_name = '해시태그'
        verbose_name_plural = f'{verbose_name} 목록'


class PostLike(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return 'Post[{post_pk}] Like (User: {username})'.format(
            post_pk=self.post.pk,
            username=self.user.username,
        )

    class Meta:
        # 특정 User가 특정 Post를 좋아요 누른 정보는 unique해야함
        unique_together = (
            ('post', 'user'),
        )

fc-instagram/posts/forms.py
from django import forms

from .models import Post, Comment


class UploadFileForm(forms.Form):
    '''
    부트스트랩 의존적임!
    '''
    image_file = forms.ImageField(
        # 파일입력 위젯 사용
        widget=forms.FileInput(
            # html 위젯 설정
            # form-control-file 클래스 사용
            attrs={
                'class': 'form-control-file',
            }
        )
    )
    comment = forms.CharField(
        required=False,
        # html 렌더링 위젯으로 textarea 사용
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
            }
        )
    )

    def save(self, **kwargs):
        post = Post.objects.create(
            photo=self.cleaned_data['photo'],
            **kwargs,
        )

        # 1. comment 관련
        comment_content = self.cleaned_data.get('comment')
        if comment_content:
            post.comments.create(
                author=post.author,
                contents=comment_content,
            )

        # 2. post_list에서 각 Post의 댓글 목록을 출력
        return post


class CommentCreateForm(forms.Form):
    # 원래 템플릿에서 구질구질하게 하던 것들을 이렇게
    # 깔끔하게 처리할 수 있게 되었다!
    contents = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'class': 'forms-control',
                'rows': 2,
            }
        )
    )

    def save(self, post, **kwargs):
        contents = self.cleaned_data['contents']
        return post.comments.create(
            contents=contents,
            **kwargs,
        )


class PostForm(forms.ModelForm):
    comment = forms.CharField(
        label='내용',
        required=False,
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'rows': 2,
            }
        )
    )

    class Meta:
        model = Post
        fields = [
            'photo',
        ]
        widgets = {
            'photo': forms.ClearableFileInput(
                attrs={
                    'class': 'form-control-file',
                }
            )
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            'contents',
        ]
        widgets = {
            'contents': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'rows': 2,
                }
            )
        }

fc-instagram/posts/views.py
import re

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import redirect, get_object_or_404
from django.template.loader import get_template


# from members.models import User
from django.urls import reverse

from .models import Post
from .forms import CommentForm, PostForm


def post_list(request):
    posts = Post.objects.all()
    template = get_template('posts/post_list.html')

    context = {
        'posts': posts,
        'comment_form': CommentForm(),
    }
    return HttpResponse(template.render(context, request))


@login_required
def post_create(request):
    template = get_template('posts/post_create.html')
    context = {}

    # 로그인 확인 로직
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        # request.FILES에 form에서 보낸 파일객체가 들어있음
        # 새로운 Post를 생성한다.
        #  author는 User.objects.first()
        #  photo는 request.FILES에 있는 내용을 적절히 꺼내서 쓴다
        # 완료된 후 posts:post_list로 redirect
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()

            comment_content = form.cleaned_data['comment']
            if comment_content:
                # 어떤 모델의 어느 속성에 제대로 바인딩 중인지
                # 확인하면 올바르게 입력 가능!
                post.comments.create(
                    author=request.user,
                    contents=comment_content,
                )

            return redirect('posts:post_list')

    else:
        # GET으로 오면 빈 Form 인스턴스를 context에 담아 전달.
        # Template에서는 'form'키로 Form 인스턴스 속성을 사용함.
        form = PostForm()

    context['form'] = form
    return HttpResponse(template.render(context, request))


def comment_create(request, post_pk):
    if request.method == 'POST':
        post = Post.objects.get(pk=post_pk)
        # 댓글 작성 form 형태에서 값 받아옴.
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()

            return redirect('posts:post_list')


def tag_post_list(request, tag_name):
    # 포스트 중, 자신에게 속한 comment 가 가진 '유일한' Hashtags 목록 중
    # tag_name이 name인 Hashtags가 포함된
    # Post 목록을 posts 변수에 할당
    # context에 담아서 render 수행.
    # HTML: /posts/tag_post_list.html
    template = get_template('posts/tag_post_list.html')
    posts = Post.objects.filter(
        comments__hashtags__tag_name=tag_name).distinct()
    context = {
        'posts': posts,
    }
    return HttpResponse(template.render(context, request))


def tag_search(request):
    # request.GET으로 전달된
    #  search_keyword값을 적절히 활용해서
    #  위의 tag_post_list view로 redirect
    # URL: '/posts/tag-search/'
    # URL Name: 'posts:tag-search'
    # Template: 없음
    search_keyword = request.GET.get('search_keyword')
    substituted_keyword = re.sub(r'#|\s+', '', search_keyword)
    return redirect('tag_post_list', substituted_keyword)


def post_like_toggle(request, post_pk):
    # url: 'posts/<post_pk>/like-toggle/
    # url name: 'posts:post_like_toggle'
    # POST 값만 처리함.

    # request.user가 post_pk에 해당하는 Post에 대해
    # Like toggle 처리를 수행.
    if request.method == 'POST':
        post = get_object_or_404(Post, pk=post_pk)
        post.like_toggle(request.user)
        url = reverse('posts:post_list')
        return redirect(url + f'#post-{post_pk}')

fc-instagram/templates/posts/post_create.html
{% extends 'common/base.html' %}

{% block content %}
    <h1 class="text-center">포스트 추가</h1>

    <div class="upload-forms">
        <form method="POST"
              enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">
                        {{ field.label }}
                    </label>
                    {{ field }}
                </div>
            {% endfor %}
            <button class="btn btn-primary btn-block">업로드</button>
        </form>
    </div>
    <!-- NoReverseMatch 에러가 뜨면 다른 템플릿의 뷰
    혹은 패턴 이름의 리버스가 제대로 되어있는지
    꼼꼼히 확인하면 오류를 찾을 수 있다! -->
    <p><a href="{% url 'posts:post_list' %}">홈으로 돌아가기</a></p>
{% endblock %}

<div class="form-group">
	<label for="id-photo">사진 첨부</label>
	<input type="file"
	       id="id-photo"
	       name="photo"
	       class="form-control-file">
</div>

fc-instagram/templates/posts/post_list.html
{% extends 'common/base.html' %}
{% load static %}

{% block content %}
<div>
    <h1 class="text-center">포스트 리스트</h1>
    {% for post in posts %}
        <!--이 div가 lg(width >= 992px)일 때, 4/12의 크기를 가지며 4/12 위치를 기준으로 시작함-->
        <div id="post-{{ post.pk }}" class="col col-lg-4 offset-lg-4 mb-4">
            <div class="card">
                <div class="card-header">
                    <span>
                        <a href="#">
                            <!-- 프로필 이미지가 없으면 출력이 안 된다! -->
                            <!-- 그래서 기본 출력값으로 빈 파일을 넣는 것!-->
                            <img src="{{ post.author.img_profile_url }}"
                                 style="width: 30px; height: 30px; border-radius: 100%">
                        </a>
                    </span>
                    <span>{{ post.author }}</span>
                </div>
                <div class="card-body">
                    <img src="{{ post.photo.url }}" class="card-img-top">

                    {% if user.is_authenticated %}
                    <form action="{% url 'posts:post_like_toggle' post_pk=post.pk %}"
                          method="POST">
                        {% csrf_token %}
                        <button class="btn btn-primary"
                                type="submit">
                            {% if user in post.like_users.all %}
                                좋아요 해제
                            {% else %}
                                좋아요
                            {% endif %}
                        </button>
                    </form>
                    {% endif %}

                    <div>
                        <span>좋아하는 사람 </span>
                        <strong>{{ post.like_users.all|join:", " }}</strong>
                    </div>


                    <ul class="list-unstyled">
                        {% for comment in post.comments.all %}
                            <li>
                                <strong>{{ comment.author }}</strong>
                                <span>{{ comment.html|safe }}</span>
                            </li>
                        {% endfor %}
                    </ul>

                    <!-- 댓글달기 영역 -->
                    <!--
                        1. 유저가 로그인 한 경우에만 보여지도록 함
                        2. 내부 요소는 textarea[name=content]와 버튼하나
                        3. action속성의 값을 위의 'comment_create' view에 해당하는 URL로 지정
                    -->
                    {% if user.is_authenticated %}
                    <form action="{% url 'posts:comment_create' post_pk=post.pk %}"
                          method="POST">
                        {% csrf_token %}
                        {{ comment_form.contents }}
                        <button class="btn btn-primary btn-block" type="submit">작성하기</button>
                    </form>
                    {% endif %}

                </div>
            </div>
        </div>
    {% endfor %}

</div>
{% endblock %}

fc-instagram/templates/posts/tag_post_list.html
{% extends 'common/base.html' %}

{% block content %}
<div class="row">
	{% for post in posts %}
		<div class="col-4">
			<div class="row square">
				<a href="#"
				   class="thumbnail"
				   style="background-image: url('{{ post.photo.url }}');"
				></a>
			</div>
		</div>
	{% endfor %}
</div>
{% endblock %}