fc-instagram/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from posts.views import tag_post_list

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='posts:post_list'), name='index'),
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('explore/tags/<str:tag_name>', tag_post_list, name='tag_post_list'),
    path('members/', include('members.urls')),
    # path('media/<path:path>', views.media_serve)
]

# 특정 디렉토리가 왔을 땐 static을 사용해서 접두사를 붙임.
#
urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

fc-instagram/members/urls.py
from django.urls import path

from . import views

app_name = 'members'
urlpatterns = [
    path('login/', views.login_view, name='login_view'),
    path('logout/', views.logout_view, name='logout_view'),
    path('register/', views.register_view, name='register_view'),
    path('profile/', views.profile_view, name='profile_view'),
    path('facebook-login/', views.facebook_login, name='facebook_login'),
]

fc-instagram/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('',
         views.post_list,
         name='post_list'),
    path('upload/',
         views.post_create,
         name='post_create'),
    # post의 pk를 찾을 때 이렇게 함.
    path('<int:post_pk>/comments/create/',
         views.comment_create,
         name='comment_create'),
    path('tag_search/',
         views.tag_search,
         name='tag_search'),
    path('<int:post_pk>/like_toggle/',
         views.post_like_toggle,
         name='post_like_toggle'),
]

fc-instagram/templates/common/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>짭스타그램</title>
    <!-- 브라우저별 기본 CSS 값 세팅-->
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <style>
        .square {

        }
        .square:before {
            content: '';
            padding: 50% 0;
            display: inline-block;
        }
        .square > .thumbnail {
            display: block;
            width: 100%;
            background-size: cover;
            background-position: center center;
        }
        .messages-container {
			position: fixed;
			top: 10px;
			left: 10px;
			width: 300px;
		}
	</style>
</head>
<body>
    <div id="wrapper">
        <!-- 내비게이션 바 시작 -->
        <nav class="navbar navbar-expand-sm bg-light">
            <a href="{% url 'posts:post_list' %}" class="navbar-brand">짭스타그램</a>
            <form action="{% url 'posts:tag_search' %}" class="form-inline ml-md-auto">
                <input type="text"
                       name="search_keyword"
                       class="form-control"
                       placeholder="검색">
            </form>
            <ul class="navbar-nav ml-md-auto">
                <li class="nav-item mr-sm-1">
                    <a href="{% url 'posts:post_create' %}"
                       class="btn btn-outline-secondary">포스트하기</a>
                </li>
                <li class="nav-item mr-sm-1">
                    <a href="#" class="btn btn-outline-secondary">Explore</a>
                </li>
                <li class="nav-item mr-sm-1">
                    <a href="#" class="btn btn-outline-secondary">Favorites</a>
                </li>

                <li class="nav-item mr-sm-1">
                    <a href="{% url 'members:profile_view' %}"
                       class="btn btn-outline-secondary">
                        {% if user.is_authenticated %}
                            {{ user.username }}의 프로필
                        {% else %}
                            로그인 해주세요!
                        {% endif %}
                    </a>
                </li>

                {% if user.is_authenticated %}
                <li class="nav-item">
                    <form action="{% url 'members:logout_view' %}"
                          method="POST">
                            {% csrf_token %}
                            <button type="submit"
                                    class="btn btn-outline-secondary">로그아웃</button>
                    </form>
                </li>
                {% else %}
                <li class="nav-item mr-sm-1">
                    <a href="{% url 'members:login_view' %}"
                       class="btn btn-outline-secondary">로그인</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'members:register_view' %}"
                       class="btn btn-outline-secondary">회원가입</a>
                </li>
                {% endif %}
            </ul>
        </nav>

        <div class="container-fluid mt-3">
            {% block content %}
            {% endblock %}
        </div>

        {% if messages %}
            <div class="messages-container">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>

    {% block script %}
        <script>
            var a = 3;
        </script>
        <script src=""></script>
    {% endblock %}
</body>
</html>